repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.77.7
    hooks:
      - id: cfn-lint
        description: Checks for templates best practice, reduce errors, and enhanced maintainability
        exclude: '.pre-commit-config.yaml|buildspec.yaml'
  - repo: https://github.com/stelligent/cfn_nag
    rev:  v0.8.10
    hooks:
    - id: cfn-nag
      exclude: '.pre-commit-config.yaml|buildspec.yaml'
      entry: cfn_nag_scan --input-path
      description: Identify common security risks and helps create a more secure and reliable IaC
      language: ruby
      files: templates/
